# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-05 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, verbose_name='\u9879\u76ee\u7f16\u53f7')),
                ('start_date', models.DateField(auto_now=True, verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(blank=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
    ]
